import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import api from "../lib/api";
import { getErrorMessage } from "../lib/errors";
import { OFFLINE_MK } from "../lib/offlineMutations";
import type { ApiResponse, Job, PaginatedResponse } from "../types";
import toast from "../lib/toast";

interface JobsParams {
  page?: number;
  limit?: number;
  search?: string;
  status?: string;
  type?: string;
  date?: string;
  /** "true" = only archived, "all" = both, omitted = active only (default). */
  archived?: string;
  /** Jobs generated by a specific RecurringJob template. */
  recurringJobId?: string;
}

export function useJobs(params: JobsParams = {}) {
  return useQuery({
    queryKey: ["jobs", params],
    queryFn: () => api.get<PaginatedResponse<Job>>("/jobs", { params }),
  });
}

export const jobQueryKey = (id: string) => ["job", id] as const;

export async function fetchJob(id: string): Promise<Job> {
  const res = await api.get<ApiResponse<Job>>(`/jobs/${id}`);
  return res.data;
}

export function useJob(id: string) {
  return useQuery({
    queryKey: jobQueryKey(id),
    queryFn: () => fetchJob(id),
    enabled: !!id,
  });
}

// Job type is free text (not a fixed lookup) so the office can type a new
// service type straight into the form. This returns the built-in suggestions
// plus every distinct type already used, so a custom type typed once shows up
// as a pick for every job after that.
export function useJobTypes() {
  return useQuery({
    queryKey: ["jobs", "types"],
    queryFn: async () => {
      const res = await api.get<ApiResponse<string[]>>("/jobs/types");
      return res.data;
    },
    staleTime: 60_000,
  });
}

export function useCreateJob() {
  const qc = useQueryClient();
  return useMutation({
    // Keyed to the offline default so a new job created with no signal
    // replays after an app reload (see lib/offlineMutations.ts). Unlike an
    // edit, there's no existing job to optimistically patch -- the new job
    // simply won't appear in lists/dispatch until the create actually syncs.
    mutationKey: OFFLINE_MK.createJob,
    mutationFn: (payload: Partial<Job>) =>
      api.post<ApiResponse<Job>>("/jobs", payload),
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: ["jobs"] });
      void qc.invalidateQueries({ queryKey: ["dispatch"] });
      toast.success("Job created successfully");
    },
    onError: (err: unknown) => {
      toast.error(getErrorMessage(err, "Failed to create job"));
    },
  });
}

export function useUpdateJob() {
  const qc = useQueryClient();
  return useMutation({
    // Keyed to the offline default so a full job edit with no signal replays
    // after an app reload (see lib/offlineMutations.ts). The
    // `expectedUpdatedAt` conflict check is a plain timestamp comparison, so
    // it stays correct no matter how long the edit sits queued.
    mutationKey: OFFLINE_MK.updateJob,
    mutationFn: ({
      id,
      expectedUpdatedAt,
      ...payload
    }: Partial<Job> & { id: string; expectedUpdatedAt?: string }) =>
      api.put<ApiResponse<Job>>(`/jobs/${id}`, {
        ...payload,
        expectedUpdatedAt,
      }),
    onMutate: (vars) => {
      // Reflect the edit immediately, since offline the real response won't
      // arrive until reconnect -- otherwise the tech is bounced back to a
      // job detail page that still shows the old values with no sign their
      // edit "took". (The assigned-technicians list itself only updates once
      // the real sync completes -- it's a separate `technicians` relation,
      // not one of these plain fields. `expectedUpdatedAt` rides along too;
      // it's not a real Job field, but it's an inert extra property here.)
      const { id, ...patch } = vars;
      qc.setQueryData(jobQueryKey(id), (old: Job | undefined) =>
        old ? { ...old, ...patch } : old,
      );
    },
    onSuccess: (_data, vars) => {
      void qc.invalidateQueries({ queryKey: ["jobs"] });
      void qc.invalidateQueries({ queryKey: ["job", vars.id] });
      void qc.invalidateQueries({ queryKey: ["dispatch"] });
      toast.success("Job updated successfully");
    },
    onError: (err: unknown, vars) => {
      // On a stale-job conflict (409), refetch the job so the next save
      // attempt has the latest `updatedAt` instead of failing again.
      void qc.invalidateQueries({ queryKey: ["job", vars.id] });
      toast.error(getErrorMessage(err, "Failed to update job"));
    },
  });
}

export function useUpdateJobStatus() {
  const qc = useQueryClient();
  return useMutation({
    // Keyed to the offline default so a status change made with no signal
    // replays after an app reload (see lib/offlineMutations.ts).
    mutationKey: OFFLINE_MK.updateJobStatus,
    mutationFn: ({
      id,
      status,
      notes,
    }: {
      id: string;
      status: string;
      notes?: string;
    }) => api.patch<ApiResponse<Job>>(`/jobs/${id}/status`, { status, notes }),
    onSuccess: (_data, vars) => {
      void qc.invalidateQueries({ queryKey: ["jobs"] });
      void qc.invalidateQueries({ queryKey: ["job", vars.id] });
      void qc.invalidateQueries({ queryKey: ["dispatch"] });
      toast.success("Job status updated");
    },
    onError: (err: unknown) => {
      toast.error(getErrorMessage(err, "Failed to update status"));
    },
  });
}

// Permanent removal -- kept for genuine data cleanup, but the UI leads with
// useArchiveJob below instead, which is reversible.
export function useDeleteJob() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => api.delete<ApiResponse<null>>(`/jobs/${id}`),
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: ["jobs"] });
      void qc.invalidateQueries({ queryKey: ["dispatch"] });
      toast.success("Job deleted");
    },
    onError: (err: unknown) => {
      toast.error(getErrorMessage(err, "Failed to delete job"));
    },
  });
}

export function useArchiveJob() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) =>
      api.post<ApiResponse<Job>>(`/jobs/${id}/archive`),
    onSuccess: (_data, id) => {
      void qc.invalidateQueries({ queryKey: ["jobs"] });
      void qc.invalidateQueries({ queryKey: ["job", id] });
      void qc.invalidateQueries({ queryKey: ["dispatch"] });
      toast.success("Job archived");
    },
    onError: (err: unknown) => {
      toast.error(getErrorMessage(err, "Failed to archive job"));
    },
  });
}

export function useUnarchiveJob() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) =>
      api.post<ApiResponse<Job>>(`/jobs/${id}/unarchive`),
    onSuccess: (_data, id) => {
      void qc.invalidateQueries({ queryKey: ["jobs"] });
      void qc.invalidateQueries({ queryKey: ["job", id] });
      void qc.invalidateQueries({ queryKey: ["dispatch"] });
      toast.success("Job restored");
    },
    onError: (err: unknown) => {
      toast.error(getErrorMessage(err, "Failed to restore job"));
    },
  });
}

export function useAssignTechnician() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({
      jobId,
      technicianId,
      isLead,
    }: {
      jobId: string;
      technicianId: string;
      isLead?: boolean;
    }) =>
      api.post<ApiResponse<Job>>(`/jobs/${jobId}/technicians`, {
        technicianId,
        isLead,
      }),
    onSuccess: (_data, vars) => {
      void qc.invalidateQueries({ queryKey: ["job", vars.jobId] });
      void qc.invalidateQueries({ queryKey: ["dispatch"] });
      toast.success("Technician assigned");
    },
    onError: (err: unknown) => {
      toast.error(getErrorMessage(err, "Failed to assign technician"));
    },
  });
}
