export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: string;
  phone?: string;
  avatar?: string;
  isActive: boolean;
  lastLogin?: string;
  createdAt: string;
  // Effective permission keys for the user's role (from /auth/login and /auth/me).
  permissions?: string[];
}

export interface Location {
  id: string;
  customerId: string;
  name: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  lat?: number;
  lng?: number;
  type: string;
  isPrimary: boolean;
}

export interface Contact {
  id: string;
  customerId: string;
  firstName: string;
  lastName: string;
  email?: string;
  phone?: string;
  role?: string;
  isPrimary: boolean;
}

export interface Customer {
  id: string;
  customerNumber: string;
  firstName: string;
  lastName: string;
  email?: string;
  phone?: string;
  mobilePhone?: string;
  type: "residential" | "commercial";
  companyName?: string;
  source?: string;
  notes?: string;
  balance: number;
  isActive: boolean;
  createdAt: string;
  locations?: Location[];
  jobs?: Job[];
  pricingTierId?: string | null;
  pricingTier?: PricingTier;
}

export interface PricingTier {
  id: string;
  name: string;
  description?: string;
  discountType: string;
  discountValue: number;
  isDefault: boolean;
  isActive: boolean;
  overrides?: PricingTierOverride[];
  _count?: { customers: number; overrides: number };
}

export interface PricingTierOverride {
  id: string;
  pricingTierId: string;
  pricebookItemId: string;
  overrideType: string;
  overrideValue: number;
  pricebookItem?: { id: string; name: string; sku?: string; unitPrice: number };
}

export interface Technician {
  id: string;
  userId: string;
  employeeId: string;
  skills: string[];
  isAvailable: boolean;
  user: User;
  vehicle?: { id: string; name: string } | null;
}

export interface JobTechnician {
  id: string;
  jobId: string;
  technicianId: string;
  isLead: boolean;
  status: string;
  technician?: Technician;
}

export interface JobScheduleBlock {
  id: string;
  jobId: string;
  start: string;
  end: string;
  note?: string | null;
  createdAt?: string;
}

export interface Job {
  id: string;
  jobNumber: string;
  customerId: string;
  locationId?: string;
  type: string;
  status: string;
  priority: string;
  summary: string;
  description?: string;
  scheduledStart?: string;
  scheduledEnd?: string;
  actualStart?: string;
  actualEnd?: string;
  notes?: string;
  techNotes?: string;
  totalAmount: number;
  isArchived: boolean;
  archivedAt?: string;
  createdAt: string;
  updatedAt: string;
  recurringJobId?: string;
  customer?: Customer;
  location?: Location;
  technicians?: JobTechnician[];
  scheduleBlocks?: JobScheduleBlock[];
  // Present when this job was auto-generated by a RecurringJob schedule (the
  // labor side of a recurring arrangement -- see ServiceAgreement/Invoice for
  // the separate billing side).
  recurringJob?: { id: string; summary: string; frequency: string };
  // Invoices billed for this work order -- ties the labor record back to the
  // monetary side so the two forms stay visibly connected.
  invoices?: {
    id: string;
    invoiceNumber: string;
    status: string;
    total: number;
    balance: number;
  }[];
}

export interface EstimateLineItem {
  id?: string;
  estimateId?: string;
  type: string;
  name: string;
  description?: string;
  quantity: number;
  unitPrice: number;
  total: number;
  sortOrder: number;
}

export interface Estimate {
  id: string;
  estimateNumber: string;
  customerId: string;
  jobId?: string;
  status: string;
  title: string;
  summary?: string;
  validUntil?: string;
  subtotal: number;
  discountType?: string;
  discountValue?: number;
  taxRate: number;
  taxAmount: number;
  total: number;
  notes?: string;
  terms?: string;
  sentAt?: string;
  approvedAt?: string;
  createdAt: string;
  customer?: Customer;
  lineItems?: EstimateLineItem[];
}

export interface InvoiceLineItem {
  id?: string;
  invoiceId?: string;
  type: string;
  name: string;
  description?: string;
  quantity: number;
  unitPrice: number;
  total: number;
  sortOrder: number;
  /** Whether this line counts toward the total and appears on the customer
   * PDF/email. Defaults to true when omitted. */
  includeOnDocument?: boolean;
}

export interface Payment {
  id: string;
  invoiceId: string;
  customerId: string;
  amount: number;
  method: string;
  status: string;
  referenceNumber?: string;
  notes?: string;
  paidAt: string;
  createdAt: string;
}

export interface Invoice {
  id: string;
  invoiceNumber: string;
  customerId: string;
  jobId?: string;
  estimateId?: string;
  serviceAgreementId?: string;
  status: string;
  dueDate?: string;
  subtotal: number;
  discountType?: string;
  discountValue?: number;
  taxRate: number;
  taxAmount: number;
  total: number;
  amountPaid: number;
  balance: number;
  notes?: string;
  terms?: string;
  sentAt?: string;
  paidAt?: string;
  createdAt: string;
  customer?: Customer;
  job?: {
    id: string;
    jobNumber: string;
    summary?: string;
    status?: string;
    purchaseOrders?: {
      id: string;
      poNumber: string;
      status: string;
      totalAmount: number;
    }[];
  };
  // Present when this invoice was generated for a ServiceAgreement billing
  // cycle (the monetary side -- see Job/RecurringJob for the labor side).
  serviceAgreement?: {
    id: string;
    agreementNumber: string;
    name: string;
  };
  lineItems?: InvoiceLineItem[];
  payments?: Payment[];
}

export interface PricebookItem {
  id: string;
  categoryId: string;
  sku: string;
  name: string;
  description?: string;
  type: string;
  unitCost: number;
  unitPrice: number;
  unit: string;
  taxable: boolean;
  isActive: boolean;
  /** Customer-tier-adjusted price; equals unitPrice when no customerId was requested. */
  effectivePrice?: number;
}

export interface PricebookCategory {
  id: string;
  name: string;
  description?: string;
  parentId?: string;
  isActive: boolean;
  items?: PricebookItem[];
}

// Numeric fields backed by Prisma `Decimal` arrive over JSON as strings; the UI
// coerces them with Number(...) at display/compute sites.

export interface StockLocation {
  id: string;
  name: string;
  code: string;
  type: string; // stockLocationType lookup: "warehouse" | "truck"
  vehicleId?: string;
  address?: string;
  isDefault: boolean;
  isActive: boolean;
  vehicle?: { id: string; name: string; licensePlate?: string };
  stock?: InventoryStock[];
  _count?: { stock: number };
}

export interface InventoryStock {
  id: string;
  inventoryItemId: string;
  stockLocationId: string;
  quantityOnHand: number;
  quantityReserved: number;
  lastCountDate?: string;
  stockLocation?: { id: string; name: string; code: string; type: string };
  inventoryItem?: { id: string; sku: string; name: string; unit: string };
}

export interface Vendor {
  id: string;
  vendorNumber: string;
  name: string;
  contactName?: string;
  email?: string;
  phone?: string;
  website?: string;
  address1?: string;
  address2?: string;
  city?: string;
  state?: string;
  zip?: string;
  country?: string;
  paymentTerms?: string;
  taxId?: string;
  notes?: string;
  isActive: boolean;
  items?: InventoryItemVendor[];
  _count?: { items: number; purchaseOrders: number };
}

export interface InventoryItemVendor {
  id: string;
  inventoryItemId: string;
  vendorId: string;
  vendorSku?: string;
  unitCost: number;
  leadTimeDays?: number;
  minimumOrderQty?: number;
  isPrimary: boolean;
  isActive: boolean;
  vendor?: { id: string; name: string };
}

export interface InventoryItemCostHistory {
  id: string;
  inventoryItemId: string;
  oldUnitCost: number;
  newUnitCost: number;
  changeSource: string;
  quantityOnHand?: number;
  receiptQuantity?: number;
  receiptUnitCost?: number;
  createdAt: string;
}

export interface InventoryItem {
  id: string;
  sku: string;
  name: string;
  description?: string;
  pricebookItemId?: string;
  categoryId?: string;
  unit: string;
  unitCost: number; // perpetual weighted-average cost
  defaultVendorId?: string;
  minQuantity: number;
  maxQuantity: number;
  reorderPoint: number;
  reorderQuantity: number;
  leadTimeDays?: number;
  isSerialized: boolean;
  isStockItem: boolean;
  isActive: boolean;
  isArchived: boolean;
  notes?: string;
  // Computed / included by the API
  totalOnHand?: number;
  isLowStock?: boolean;
  stock?: InventoryStock[];
  defaultVendor?: { id: string; name: string };
  vendors?: InventoryItemVendor[];
  transactions?: InventoryTransaction[];
  costHistory?: InventoryItemCostHistory[];
}

export interface InventoryTransaction {
  id: string;
  inventoryItemId: string;
  stockLocationId: string;
  type: string;
  quantity: number;
  unitCost?: number;
  quantityBefore?: number;
  quantityAfter?: number;
  referenceType?: string;
  referenceId?: string;
  referenceNumber?: string;
  jobId?: string;
  notes?: string;
  transactionDate: string;
  createdAt: string;
  stockLocation?: { id: string; name: string; code: string };
}

export interface POLineReceipt {
  id: string;
  poLineId: string;
  receiptNumber: string;
  quantityReceived: number;
  unitCost: number;
  totalCost: number;
  stockLocationId?: string;
  receivedAt: string;
  status: string;
  documentNumber?: string;
  serialNumbers: string[];
  lotNumber?: string;
  notes?: string;
  isReturn: boolean;
  stockLocation?: { id: string; name: string; code: string };
}

export interface POLine {
  id: string;
  purchaseOrderId: string;
  inventoryItemId?: string;
  lineType: string;
  lineNumber: number;
  description: string;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
  receivedQuantity: number;
  lineStatus: string;
  notes?: string;
  inventoryItem?: { id: string; sku: string; name: string; unit: string };
  receipts?: POLineReceipt[];
}

export interface PurchaseOrder {
  id: string;
  poNumber: string;
  vendorId: string;
  status: string;
  shipToLocationId?: string;
  jobId?: string;
  customerId?: string;
  orderDate: string;
  expectedDate?: string;
  receivedDate?: string;
  subtotal: number;
  taxAmount: number;
  shippingCost: number;
  totalAmount: number;
  deliveryTerms?: string;
  notes?: string;
  vendor?: { id: string; name: string };
  shipToLocation?: { id: string; name: string; code: string };
  job?: { id: string; jobNumber: string; summary?: string };
  customer?: {
    id: string;
    firstName: string;
    lastName: string;
    companyName?: string;
  };
  lines?: POLine[];
  _count?: { lines: number };
}

/** A consumable part issued to a job (derived from issue transactions). */
export interface JobPart {
  transactionId: string;
  inventoryItemId: string;
  sku: string;
  name: string;
  unit: string;
  stockLocation?: { id: string; name: string; code: string };
  quantityUsed: number;
  unitCost: number;
  unitPrice: number;
  total: number;
  transactionDate: string;
  notes?: string;
}

export interface ReorderSuggestionGroup {
  vendor: { id: string | null; name: string };
  lines: {
    inventoryItemId: string;
    sku: string;
    name: string;
    onHand: number;
    reorderPoint: number;
    suggestedQuantity: number;
    unitCost: number;
  }[];
}

export interface InventoryReport {
  totals: {
    totalItems: number;
    totalValue: number;
    lowStockCount: number;
    received30d: number;
  };
  valueByLocation: {
    id: string;
    name: string;
    code: string;
    type: string;
    value: number;
    items: number;
  }[];
  topItemsByValue: {
    id: string;
    sku: string;
    name: string;
    onHand: number;
    unitCost: number;
    value: number;
  }[];
  recentCostChanges: {
    id: string;
    sku: string;
    name: string;
    oldUnitCost: number;
    newUnitCost: number;
    changeSource: string;
    createdAt: string;
  }[];
  poByStatus: { status: string; count: number; total: number }[];
}

export interface VehicleOption {
  id: string;
  name: string;
  licensePlate?: string;
  technicians?: { user: { firstName: string; lastName: string } }[];
  stockLocation?: { id: string; name: string; code: string } | null;
}

export interface QuickBooksSettings {
  id: string;
  isEnabled: boolean;
  companyFileName?: string;
  webConnectorUsername: string;
  hasPassword: boolean;
  salesTaxItemName: string;
  depositToAccountName?: string;
  appId: string;
  appName: string;
  lastSyncStartedAt?: string;
  lastSyncCompletedAt?: string;
}

export interface QuickBooksSyncQueueItem {
  id: string;
  entityType: string;
  entityId: string;
  entityLabel?: string | null;
  operation: string;
  status: string;
  requestId?: string;
  attempts: number;
  lastError?: string;
  lastAttemptAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface QuickBooksMappingRecord {
  id: string;
  entityType: string;
  entityId: string;
  quickbooksId: string;
  editSequence?: string;
  lastSyncedAt: string;
}

export interface QuickBooksItemMappingRecord {
  id: string;
  lineItemType?: string;
  pricebookItemId?: string;
  quickbooksItemName: string;
  isActive: boolean;
  pricebookItem?: { id: string; name: string; sku?: string };
}

export interface SerializedUnit {
  id: string;
  serialNumber: string;
  inventoryItemId: string;
  status: string;
  stockLocationId?: string;
  sourceReceiptId?: string;
  purchaseCost?: number;
  installedCustomerId?: string;
  installedLocationId?: string;
  installedJobId?: string;
  equipmentId?: string;
  installedAt?: string;
  warrantyMonths?: number;
  warrantyExpiresAt?: string;
  notes?: string;
  createdAt: string;
  inventoryItem?: {
    id: string;
    sku: string;
    name: string;
    pricebookItem?: { unitPrice: number; name: string } | null;
  };
  stockLocation?: { id: string; name: string; code: string };
}

export interface AgreementVisit {
  id: string;
  agreementId: string;
  name: string;
  scheduledDate?: string;
  completedDate?: string;
  jobId?: string;
  status: string;
}

export interface ServiceAgreement {
  id: string;
  agreementNumber: string;
  customerId: string;
  name: string;
  status: string;
  startDate: string;
  endDate: string;
  billingFrequency: string;
  amount: number;
  autoRenew: boolean;
  nextBillingDate?: string;
  lastSentAt?: string;
  terms?: string;
  notes?: string;
  customer?: Customer;
  visits?: AgreementVisit[];
}

export interface Campaign {
  id: string;
  name: string;
  type: string;
  status: string;
  budget?: number;
  startDate?: string;
  endDate?: string;
  trackingNumber?: string;
  notes?: string;
  isArchived?: boolean;
  archivedAt?: string;
}

export interface Call {
  id: string;
  customerId?: string;
  direction: string;
  status: string;
  fromNumber: string;
  toNumber: string;
  duration?: number;
  reason?: string;
  campaignId?: string;
  notes?: string;
  createdAt: string;
  customer?: Customer;
}

export interface CustomerMessage {
  id: string;
  customerId: string;
  direction: string;
  channel: string;
  subject?: string;
  body: string;
  sentAt: string;
  sentById?: string;
  createdAt: string;
  customer?: {
    id: string;
    firstName: string;
    lastName: string;
    companyName?: string;
  };
  sentBy?: { id: string; firstName: string; lastName: string };
}

export interface Notification {
  id: string;
  userId: string;
  title: string;
  message: string;
  type: string;
  link?: string;
  isRead: boolean;
  createdAt: string;
}

export interface CompanySettings {
  id: string;
  name: string;
  logo?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  phone?: string;
  email?: string;
  website?: string;
  taxRate: number;
  currency: string;
  timezone: string;
}

export interface BusinessUnit {
  id: string;
  name: string;
  type: string;
  isActive: boolean;
}

// ── Metadata / lookups (DB-driven single source of truth for enums) ──────────
export interface LookupOption {
  value: string;
  label: string;
  color?: string | null;
  sortOrder: number;
}

/** Known lookup categories served by GET /api/v1/metadata. */
export type LookupCategory =
  | "jobStatus"
  | "jobPriority"
  | "jobType"
  | "jobTechnicianStatus"
  | "estimateStatus"
  | "invoiceStatus"
  | "paymentMethod"
  | "paymentStatus"
  | "userRole"
  | "customerType"
  | "locationType"
  | "lineItemType"
  | "discountType"
  | "agreementStatus"
  | "billingFrequency"
  | "agreementVisitStatus"
  | "campaignType"
  | "campaignStatus"
  | "callDirection"
  | "callStatus"
  | "inventoryTransactionType"
  | "pricebookItemType"
  | "notificationType"
  | "equipmentType"
  | "equipmentCondition"
  | "businessUnitType"
  | "stockLocationType"
  | "poStatus"
  | "poLineType"
  | "poLineStatus"
  | "receiptStatus"
  | "serializedUnitStatus"
  | "costChangeSource"
  | "quickbooksEntityType"
  | "quickbooksSyncOperation"
  | "quickbooksSyncStatus"
  | "pricingOverrideType"
  | "messageDirection"
  | "messageChannel";

export type Metadata = Partial<Record<LookupCategory, LookupOption[]>>;

export interface EquipmentServiceJob {
  id: string;
  jobNumber: string;
  summary: string;
  type?: string;
  status: string;
  scheduledStart?: string;
  completedAt?: string;
  totalAmount?: number;
}

export interface Equipment {
  id: string;
  customerId?: string;
  locationId?: string;
  jobId?: string;
  name: string;
  type?: string;
  manufacturer?: string;
  model?: string;
  serialNumber?: string;
  description?: string;
  installDate?: string;
  warrantyExpiry?: string;
  partsWarrantyExpiry?: string;
  replaceByDate?: string;
  condition?: string;
  notes?: string;
  createdAt: string;
  customer?: {
    id: string;
    firstName: string;
    lastName: string;
    companyName?: string;
  };
  location?: {
    id: string;
    name?: string;
    address: string;
    city: string;
    state: string;
  };
  serviceHistory?: EquipmentServiceJob[];
}

// Entity types that can own image/file attachments. Mirrors the backend
// ALLOWED_TYPES in attachments.controller.js.
export type AttachmentEntityType =
  "job" | "estimate" | "invoice" | "inventory" | "customer" | "equipment";

export interface Attachment {
  id: string;
  entityType: AttachmentEntityType;
  entityId: string;
  filename: string;
  mimeType: string;
  size: number;
  caption?: string | null;
  uploadedById?: string | null;
  createdAt: string;
}

export interface ApiResponse<T> {
  success: boolean;
  data: T;
  error?: string;
}

export interface PermissionDef {
  key: string;
  label: string;
}

export interface PermissionGroup {
  group: string;
  permissions: PermissionDef[];
}

export interface RolePermissions {
  role: string;
  label: string;
  isSystem: boolean;
  permissions: string[];
}

export interface AuditLogEntry {
  id: string;
  userId?: string;
  userEmail?: string;
  userRole?: string;
  action: string;
  method: string;
  path: string;
  entity?: string;
  entityId?: string;
  statusCode: number;
  metadata?: string;
  ip?: string;
  createdAt: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}
